version: '3.9'
services:
  laravel:
    container_name: laravel
    image: miki-laravel
    command: bash -c "
        composer install &&
        php artisan serve --host=0.0.0.0
        "
    volumes:
      - .:/app
    ports:
      - 2324:8000

  scheduler:
    container_name: scheduler
    image: miki-laravel
    command: 'php artisan schedule:work'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - laravel
